config/routes.rb
Rails.application.routes.draw do
  resources :quizzes do
    member do
      get 'correct'
      get 'wrong'
    end
  end
  resources :categories
  resources :fields

  root 'quizzes#index'

  get 'getquiz' => 'quizzes#quizme'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :quizzes, dependent: :destroy
  belongs_to :field
  before_destroy :used_by_quiz
  validates :name, presence: true
  validates :name, uniqueness: true

  def used_by_quiz
    if quizzes.empty?
      return true
    else
      errors.add(:base, 'Quiz depending on this')
      return false
    end
  end

end

app/models/field.rb
class Field < ActiveRecord::Base
  has_many :quiz
  has_many :category, dependent: :destroy
  before_destroy :used_by_category
  validates :name, presence: true
  validates :name, uniqueness: true

  def used_by_category
    if category.empty?
      return true
    else
      errors.add(:base, 'Quiz depending on this')
      return false
    end
  end

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :category
  belongs_to :field
  validates :category_id, presence: true
  validates :field_id, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :field_id)
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def quizme
    @quiz = Quiz.order("RAND()").limit(1).first
  end

  def correct
    @quiz = Quiz.find(params[:id])
    @quiz.was_correct = true
    if @quiz.save
      redirect_to '/getquiz'
    end
  end

  def wrong
    @quiz = Quiz.find(params[:id])
    @quiz.was_correct = false
    if @quiz.save
      redirect_to '/getquiz'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:field_id, :category_id, :question, :answer, :last, :was_correct)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :field %><br>
    <%= f.collection_select(:field_id, Field.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Field</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <% @fields = Field.all %>
      <tr>
        <td><%= category.name %></td>
        <td><%= @fields.find_by(category.field_id).name %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'You Sure?' } %></td>
      </tr>
    <% end %>
  <tr>
    <td><%= link_to 'New Category', new_category_path %></td>
  </tr>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Field:</strong>
  <%= @category.field_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Fields</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.name %></td>
        <td><%= link_to 'Edit', edit_field_path(field) %></td>
        <td><%= link_to 'Delete', field, method: :delete, data: { confirm: 'You Sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller.controller_name %>">

<div id="banner">
  <%= link_to "http://localhost:3000" do %>
    <%= image_tag("logo.png") %>
  <% end %>
  <%= @page_title || "QuizMe" %>
</div>
<div id="columns">
  <div id="side">
    <ul>
      <li><a href="http://localhost:3000">Home</a></li>
      <li><a href="http://localhost:3000/getquiz">QuizMe</a></li>
      <li><a href="http://localhost:3000/categories">Categories</a></li>
      <li><a href="http://localhost:3000/fields">Fields</a></li>
    </ul>
  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :field_id %><br>
    <%= f.collection_select(:field_id, Field.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Field</th>
      <th>Cat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <% @category = Category.find_by(quiz.category_id) %>
      <% @field = Field.find_by(quiz.field_id) %>
      <tr class="<%= cycle('quiz_line_odd', 'quiz_line_even') %>">
        <td><%= quiz.question %></td>
        <!-- <td><%= truncate(quiz.answer, :length => 100, :omission => "...", :escape =>  false) %></td> -->
        <td><%= quiz.answer %></td>
        <td><%= @field.name %></td>
        <td><%= @category.name %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Delete', quiz, method: :delete, data: { confirm: 'You Sure?' } %></td>
      </tr>
    <% end %>
  <tr>
    <td><%= link_to 'New Quiz', new_quiz_path %></td>
  </tr>
  </tbody>
</table>

<br>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/quizme.html.erb
<div class="entry">
  <p>
    <h1><%= @quiz.question %></h1>
  </p>

  <p>
    <h2 class="answer"><%= @quiz.answer %></h2>
    <%= button_tag "Show", :id => "show_answer" %>
  </p>

  <p>
    <table>
      <tr>
        <td><%= link_to "Correct", correct_quiz_path(@quiz) %></td>
        <td><%= link_to "Wrong", wrong_quiz_path(@quiz) %></td>
      </tr>
    </table>
  </p>

</div>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Field:</strong>
  <%= @quiz.field_id %>
</p>

<p>
  <strong>Cat:</strong>
  <%= @quiz.category_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @quiz.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @quiz.answer %>
</p>

<p>
  <strong>Last:</strong>
  <%= @quiz.last %>
</p>

<p>
  <strong>Was correct:</strong>
  <%= @quiz.was_correct %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>